/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SettingsImport } from './routes/settings'
import { Route as PinsImport } from './routes/pins'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as GuildsGuildIdImport } from './routes/guilds.$guildId'

// Create/Update Routes

const SettingsRoute = SettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const PinsRoute = PinsImport.update({
  id: '/pins',
  path: '/pins',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const GuildsGuildIdRoute = GuildsGuildIdImport.update({
  id: '/guilds/$guildId',
  path: '/guilds/$guildId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/pins': {
      id: '/pins'
      path: '/pins'
      fullPath: '/pins'
      preLoaderRoute: typeof PinsImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
    '/guilds/$guildId': {
      id: '/guilds/$guildId'
      path: '/guilds/$guildId'
      fullPath: '/guilds/$guildId'
      preLoaderRoute: typeof GuildsGuildIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/pins': typeof PinsRoute
  '/settings': typeof SettingsRoute
  '/guilds/$guildId': typeof GuildsGuildIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/pins': typeof PinsRoute
  '/settings': typeof SettingsRoute
  '/guilds/$guildId': typeof GuildsGuildIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/pins': typeof PinsRoute
  '/settings': typeof SettingsRoute
  '/guilds/$guildId': typeof GuildsGuildIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/pins' | '/settings' | '/guilds/$guildId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/pins' | '/settings' | '/guilds/$guildId'
  id: '__root__' | '/' | '/about' | '/pins' | '/settings' | '/guilds/$guildId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PinsRoute: typeof PinsRoute
  SettingsRoute: typeof SettingsRoute
  GuildsGuildIdRoute: typeof GuildsGuildIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PinsRoute: PinsRoute,
  SettingsRoute: SettingsRoute,
  GuildsGuildIdRoute: GuildsGuildIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/pins",
        "/settings",
        "/guilds/$guildId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/pins": {
      "filePath": "pins.tsx"
    },
    "/settings": {
      "filePath": "settings.tsx"
    },
    "/guilds/$guildId": {
      "filePath": "guilds.$guildId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
