name: Publish to GitHub Container Registry

on:
  push:
    branches:
      - 'master'
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: haya14busa/action-cond@v1
        id: checkpr
        with:
          cond: ${{ github.event_name == 'pull_request' }}
          if_true: false
          if_false: true
      - name: Checkout repository
        uses: actions/checkout@v3.2.0
        with:
          submodules: 'recursive'

      - name: Log in to the Container registry
        uses: docker/login-action@master
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x.x'
          cache: true
          cache-dependency-path: "*/packages.lock.json"
          
      - uses: pnpm/action-setup@v4
        with:
          package_json_file: 'Gouda.Web/package.json'

      - name: Restore .NET
        run: |
          dotnet restore --locked-mode
          
      - name: Build .NET
        run: |
          dotnet build --no-restore
          
      - name: Start Local Docker registry
        run: |
          docker run -d -p 5000:5000 --restart=always --name registry registry:2
          
      - name: Build base Docker image
        run: |
          docker build -t localhost:5000/gouda/bot-base .
          docker image push localhost:5000/gouda/bot-base:latest

      - name: Install Aspirate
        run: |
          dotnet tool install -g aspirate

      - name: Deploy Aspirate
        working-directory: Gouda.AppHost
        run: |
          aspirate generate --output-format compose --include-dashboard --container-registry ghcr.io --container-image-tag "${GITHUB_REF##*/}" --non-interactive --secret-password secret --runtime-identifier linux-musl-x64
        env:
          VITE_LEAFLET_ATTRIBUTION: ${{ vars.VITE_LEAFLET_ATTRIBUTION }}
          VITE_LEAFLET_MAP_TILE_URL: ${{ secrets.VITE_LEAFLET_MAP_TILE_URL }}

      - name: Generate Job Summary
        run: |
          echo "## Docker Compose File" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat Gouda.AppHost/aspirate-output/docker-compose.yaml >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
